const REQUEST_MEETING_PENDING = "REQUEST_MEETING_PENDING";
const REQUEST_MEETING_SUCCESS = "REQUEST_MEETING_SUCCESS";
const REQUEST_MEETING_FAILED = "REQUEST_MEETING_FAILED";

const REQUEST_TOPICS_PENDING = "REQUEST_TOPICS_PENDING";
const REQUEST_TOPICS_SUCCESS = "REQUEST_TOPICS_SUCCESS";
const REQUEST_TOPICS_FAILED = "REQUEST_TOPICS_FAILED";

const CHANGE_MEETING = "CHANGE_MEETING";
const CHANGE_TOPICS = "CHANGE_TOPICS";

const START_MEETING_PENDING = "START_MEETING_PENDING";
const START_MEETING_SUCCESS = "START_MEETING_SUCCESS";
const START_MEETING_FAILED = "START_MEETING_FAILED";

const FINISH_MEETING_PENDING = "FINISH_MEETING_PENDING";
const FINISH_MEETING_SUCCESS = "FINISH_MEETING_SUCCESS";
const FINISH_MEETING_FAILED = "FINISH_MEETING_FAILED";

const ADD_TOPIC = "ADD_TOPIC";
const TOGGLE_TOPIC = "TOGGLE_TOPIC";

export enum MeetingStatus {
    Preparation,
    Started,
    Finished
}

export {
    REQUEST_MEETING_PENDING,
    REQUEST_MEETING_SUCCESS,
    REQUEST_MEETING_FAILED,
    REQUEST_TOPICS_PENDING,
    REQUEST_TOPICS_SUCCESS,
    REQUEST_TOPICS_FAILED,
    CHANGE_MEETING,
    CHANGE_TOPICS,
    START_MEETING_PENDING,
    START_MEETING_SUCCESS,
    START_MEETING_FAILED,
    FINISH_MEETING_PENDING,
    FINISH_MEETING_SUCCESS,
    FINISH_MEETING_FAILED,
    ADD_TOPIC,
    TOGGLE_TOPIC
};
