const REQUEST_MEETING_PENDING = "REQUEST_MEETING_PENDING";
const REQUEST_MEETING_SUCCESS = "REQUEST_MEETING_SUCCESS";
const REQUEST_MEETING_FAILED = "REQUEST_MEETING_FAILED";

const REQUEST_TOPICS_PENDING = "REQUEST_TOPICS_PENDING";
const REQUEST_TOPICS_SUCCESS = "REQUEST_TOPICS_SUCCESS";
const REQUEST_TOPICS_FAILED = "REQUEST_TOPICS_FAILED";

const CHANGE_MEETING = "CHANGE_MEETING";
const CHANGE_TOPICS = "CHANGE_TOPICS";

export {
    REQUEST_MEETING_PENDING,
    REQUEST_MEETING_SUCCESS,
    REQUEST_MEETING_FAILED,
    REQUEST_TOPICS_PENDING,
    REQUEST_TOPICS_SUCCESS,
    REQUEST_TOPICS_FAILED,
    CHANGE_MEETING,
    CHANGE_TOPICS
};
